name: category_picker
description: A category picker for Flutter with two-level categories, custom icons and colors.
version: 1.0.0
homepage: https://github.com/hujingxuan0604/category_picker.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
